on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "2.7"
            django-version: "1.11"
            select2: false
            test-browser: false
          - python-version: "2.7"
            django-version: "1.11"
            select2: true
            test-browser: true
          - python-version: "3.5"
            django-version: "2.0"
            select2: true
            test-browser: false
          - python-version: "3.6"
            django-version: "2.1"
            select2: false
            test-browser: false
          - python-version: "3.7"
            django-version: "3.0"
            select2: true
            test-browser: true
          - python-version: "3.8"
            django-version: "3.1"
            select2: true
            test-browser: false
          - python-version: "3.9"
            django-version: "4.0"
            select2: false
            test-browser: false
          - python-version: "3.10"
            django-version: "4.0"
            select2: true
            test-browser: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Instal pip deps
        run: |
           .github/workflows/make-requirements.txt.sh > requirements.txt
          pip install -r requirements.txt
        env:
          SELECT2: ${{ matrix.select2 }}
          DJANGO_VERSION: ${{ matrix.django-version }}
      - name: Install apt deps
        run: sudo apt-get install -y firefox-geckodriver xvfb
        if: matrix.test-browser == 'true'
      - name: Run pytest
        run: |
          ${{ matrix.test-browser == 'true' && 'xvfb-run --auto-servernum' || '' }} \
          python -m pytest \
            -vv \
            --cov django_addanother \
            --create-db \
            ${{ matrix.test-browser == 'true' && '' || '-k "not test_browser"' }} \
            test_project/testapp/tests.py
        env:
          DJANGO_SETTINGS_MODULE: test_project.settings

